version: '3'
services:
  webapp:
    build: ./kivi
    image: mykivi
    container_name: mykivi-test
    depends_on:
      - "db"
    ports:
      - "8080:80"
    volumes:
      - "./kivi/kivitendo-erp:/var/www/kivitendo-erp"
  db:
    build: ./pgsql-kivi
    image: mypgsql
    container_name: mypgsql-test
