version: '3'
services:
  kiviweb:
    build: ./web
    volumes:
      - "./web/kivitendo-erp:/var/www/kivitendo-erp"
    restart: unless-stopped
    environment:
      - TZ=Europe/Zurich
    ports:
      - "8084:80"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kiviweb.entrypoints=web"
      - "traefik.http.routers.kiviweb.rule=Host(`kivi.corp`)"

networks:
  traefik:
    external: true
    name: traefik_net

