version: '3'
services:
  web:
    build: ./web
    image: mykivi
    container_name: mykivi-run
    depends_on:
      - "db"
    ports:
      - "50100:80"
    volumes:
      - "./web/kivitendo-erp:/var/www/kivitendo-erp"
    restart: always
  db:
    build: ./db
    image: mypgsql
    container_name: mypgsql-run
    restart: always
    environment:
      - "POSTGRES_USER=kivitendo"
      - "POSTGRES_PASSWORD=mypass123"
  adminer:
    image: adminer
    restart: always
    ports:
      - "50102:8080"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "50105:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user@example.com"
      - "PGADMIN_DEFAULT_PASSWORD=1234"
