version: '3'
services:
  webapp:
    build: ./kivi
    image: mykivi
    container_name: mykivi-test
    depends_on:
      - "db"
    ports:
      - "50100:80"
    volumes:
      - "./kivi/kivitendo-erp:/var/www/kivitendo-erp"
    restart: always
  db:
    build: ./pgsql-kivi
    image: mypgsql
    container_name: mypgsql-test
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - "50102:8080"
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - "PGADMIN_DEFAULT_EMAIL=user@example.com"
#      - "PGADMIN_DEFAULT_PASSWORD=1234"
#    ports:
#      - "50105:80"
